mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from polls import views

urlpatterns = [
    path('',views.index2,name='index2'),
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name='polls'
urlpatterns = [

    path('user_login' ,views.user_login,name='user_login'),
    path('register/',views.register,name='register'),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('',views.index,name='index'),
    path('<int:question_id>/',views.detail,name='detail'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
    path('<int:question_id>/results/',views.results,name='results')
]

polls/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Question(models.Model):

    question_text=models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User,on_delete='cascade')

    portfolio_site= models.URLField(blank=True)

    def __str__(self):
        return self.user.username

polls/forms.py
from django import forms
from django.contrib.auth.models import User
from polls.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields =('username','email','password')

class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model= UserProfileInfo
        fields = ('portfolio_site',)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from polls.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse

from django.contrib.auth.decorators import login_required

from .models import Question,Choice


def index2(request):
    return render(request,'polls/index2.html')

@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index2'))

def register(request):

    registered=False

    if request.method =="POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data= request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user
            profile.save()

            registered = True

        else:

            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()




    return render(request,'polls/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index2'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to login and failed")
            print("Username:{} and password {}".format(username,password))
            return HttpResponse("Invalid credentials")
    else:
        return render(request,'polls/login.html',{})






def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request,question_id):
    question= get_object_or_404(Question,pk=question_id)
    return render(request,'polls/detail.html',{'question':question})

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})




# Create your views here.


# Create your views here.

polls/templates/polls/base.html
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-link" href="http://127.0.0.1:8000/admin/login/?next=/admin/">ADMIN</a> </li>
            <li><a class="navbar-link" href="{% url 'polls:register'%}">REGISTER</a> </li>

            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'polls:logout' %}">Logout</a> </li>
            {%else%}
            <li><a class="navbar-link" href="{% url 'polls:user_login'%}">Login</a> </li>
            {%endif%}


        </ul>
    </div>
</nav>
<div class="container">
    {% block abc %}

    {% endblock %}
</div>
</body>
</html>

polls/templates/polls/detail.html
{% extends 'polls/base.html'%}
{% block abc%}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
{% endblock%}

polls/templates/polls/index.html
{% extends 'polls/base.html'%}
{% block abc%}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock%}

polls/templates/polls/index2.html
{% extends 'polls/base.html' %}

{%block abc %}

<div class="jombotron">
    <h1> Welcome!</h1>
    {% if user.is_authenticated %}
    <h3>Click <a href="{% url 'polls:index' %}">here</a> to go to Polls</h3>
    {%else%}
    <h3>Login to go for polling</h3>
    {%endif%}

</div>

{%endblock %}

polls/templates/polls/login.html
{% extends 'polls/base.html '%}
{% block abc %}
<head>
    <meta charset="UTF-8">
    <title>{% block title %}App Music{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body background="lightslategrey">
<div class="container">

    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="card card-container">
                    <h1 class="page-title">Login</h1>
                    <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
                    <p id="profile-name" class="profile-name-card"></p>
                    <form class="form-signin" role="form" action="{% url 'polls:user_login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input class="form-control" id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <input class="form-control" id="id_password" maxlength="30" name="password" type="password" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-12">
                                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
                            </div>
                        </div>
                    </form>
                    <div class="panel-signup">
                      Don't have an account? <a class="forgot-password" href="{% url 'polls:register' %}">Click here</a> to register.
                    </div>
                    {% if error_message %}
                        <p class="error_message"><strong>{{ error_message }}</strong></p>
                    {% endif %}
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

polls/templates/polls/registration.html
{% extends 'polls/base.html'%}

{%load staticfiles%}

{% block abc%}

<a class="jombotron">
    {%if registered %}
    <h1>Thank you for registering</h1>

    {%else%}
    <h1>
        Register Here
    </h1>
    <h3>Fill out the form</h3>
    <form method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        <input type="submit" value="Register">
    </form>
    {%endif%}
</div>
{% endblock %}

polls/templates/polls/results.html
{% extends 'polls/base.html'%}
{% block abc%}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock%}